# Spring Boot YAML configuration

spring:
  application:
    name: sprint-boot-3.5-template
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
lifecycle:
  timeout-per-shutdown-phase: 30s

server:
  address: 0.0.0.0
  port: 8080
  shutdown: graceful

security:
  jwt:
    secret: change-this-secret-key-to-a-very-long-random-string-at-least-32-characters
    expiration-ms: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,metrics
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
      probes:
        enabled: true
    circuitbreakers:
      enabled: true
    metrics:
      enabled: true
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  simple:
    metrics:
      export:
        enabled: true
        step: 60s
  metrics:
    enable:
      jvm: true
      system: true
      process: true
      jdbc: true
      hikaricp: true
      auth: true
      external-api: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
  show-actuator: false

resilience4j:
  circuitbreaker:
    instances:
      externalApi:
        failure-rate-threshold: 50
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
      failingService:
        failure-rate-threshold: 100
        sliding-window-size: 5
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2

app:
  init:
    add-admin: true

info:
  app:
    name: Spring Service Template
    description: A Spring Boot 3.5 template with JWT authentication and virtual threads
    version: "@project.version@"
    encoding: "@project.build.sourceEncoding@"
    java:
      version: "@java.version@"
  build:
    timestamp: "@maven.build.timestamp@"
    artifact: "@project.artifactId@"
    group: "@project.groupId@"
  environment:
    profile: "${spring.profiles.active:default}"
    virtual-threads: "${spring.threads.virtual.enabled}"
    server:
      port: "${server.port}"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%t] %-40.40logger{39} : %m%n"
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

