spring:
  kafka: # Kafka configuration - but it depends on the provider, this configuration is for Confluent Cloud
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      sasl:
        mechanism: PLAIN
      security:
        protocol: SASL_SSL
      session:
        timeout:
          ms: 45000
        jaas:
            config: "org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_USERNAME:XXXXX}' password='${}';"
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:template-group}
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
